version: '3'

services:
  web:
    build: .
    command: bash -c "gunicorn --config gunicorn_config.py breed_classifier.wsgi:application"
    container_name: dog_breed_classifier_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"