name: Deploy to Oracle Instance with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and Push Docker images
      run: |
        docker-compose build
        docker-compose push

    - name: Deploy to Oracle Instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.ORACLE_INSTANCE_HOST }}
        username: ${{ secrets.ORACLE_INSTANCE_USERNAME }}
        password: ${{ secrets.ORACLE_INSTANCE_PASSWORD }}
        script: |
          cd dog_breed_classifier_app
          docker-compose pull
          sudo systemctl restart nginx
          sudo systemctl restart breed_classifier_app
